----------------------------------------------------------------------------------
-- Company: University of Sheffield
-- Engineer: David Cracknell
-- 
-- Create Date: 02/03/2026 01:41:15 PM
-- Design Name: 
-- Module Name: aes_optimised_key_expansion - Behavioral
-- Project Name: optimised for low area AES device
-- Target Devices: 
-- Tool Versions: 
-- Description: makes key expansions for aes function using FSM and shift registers to lower the area.
-- 
-- Dependencies: AES_SOX_PKG.vhd
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity aes_key_expansion is
    port(
        clk    : in  std_logic;
        rst    : in  std_logic;
        start  : in  std_logic;  -- Pulse high for one clock to start/restart key expansion
        key_in : in  std_logic_vector(127 downto 0);

        -- Streamed round key output (1 byte per clock when roundkey_valid = '1')
        roundkey_byte_out : out std_logic_vector(7 downto 0);
        roundkey_valid    : out std_logic;

        -- Round/byte indices intentionally removed for lean implementation (tied to zero)
        round_idx_out     : out std_logic_vector(3 downto 0);
        byte_idx_out      : out std_logic_vector(3 downto 0);

        -- Full 128-bit round key block output removed for lean implementation (tied off)
        roundkey_block_out   : out std_logic_vector(127 downto 0);
        roundkey_block_valid : out std_logic;

        -- Last round key output removed for lean implementation (tied off)
        last_roundkey_out : out std_logic_vector(127 downto 0);

        -- Status outputs
        busy : out std_logic;     -- High while streaming or generating round keys
        done : out std_logic      -- High after round 10 has been generated and streamed
    );
end entity aes_key_expansion;

architecture rtl of aes_key_expansion is

    subtype byte_t is std_logic_vector(7 downto 0);
    type byte_array16_t is array (0 to 15) of byte_t;
    type byte_array4_t  is array (0 to 3)  of byte_t;

    -- AES-128 Rcon values for rounds 1..10 (byte form, applied to g() output byte 0)
    type rcon_array_t is array (1 to 10) of byte_t;
    constant RCON_B : rcon_array_t := (
        x"01", x"02", x"04", x"08", x"10",
        x"20", x"40", x"80", x"1B", x"36"
    );

    -- FSM states:
    -- IDLE       : wait for start pulse, latch input key
    -- OUT_ROUND0 : stream the initial key (round 0 key)
    -- G_FILL     : compute g() = SubWord(RotWord(w3)) with Rcon applied (4 cycles)
    -- GEN_BYTES  : generate and stream next round key bytes (16 cycles)
    -- DONE_ST    : completed generation through round 10; wait for restart
    type state_t is (IDLE, OUT_ROUND0, G_FILL, GEN_BYTES, DONE_ST);
    signal state : state_t := IDLE;

    -- Current working round key storage (16 bytes). Updated in-place during generation.
    signal curr_key : byte_array16_t := (others => (others => '0'));

    -- g_cache stores g(w3) as 4 bytes:
    -- g(w3) = SubWord(RotWord(w3)), and Rcon is XORed into g_cache(0) only.
    signal g_cache : byte_array4_t := (others => (others => '0'));

    -- prev4 holds the last four newly generated bytes to implement:
    -- new[i] = old[i] XOR new[i-4] for i >= 4, without needing wide storage/indexing.
    signal prev4 : byte_array4_t := (others => (others => '0'));

    -- Internal counters:
    -- round_no: indicates which round key curr_key currently represents (0..10)
    -- byte_no : index within the 16-byte key during streaming/generation (0..15)
    -- g_step  : selects which byte of RotWord(w3) is being processed (0..3)
    -- p4      : rolling index into prev4 (wraps naturally in 2 bits)
    signal round_no : unsigned(3 downto 0) := (others => '0'); -- 0..10
    signal byte_no  : unsigned(3 downto 0) := (others => '0'); -- 0..15
    signal g_step   : unsigned(1 downto 0) := (others => '0'); -- 0..3
    signal p4       : unsigned(1 downto 0) := (others => '0'); -- 0..3

    -- Start edge detection (start_pulse = start rising edge)
    signal start_d : std_logic := '0';

    -- Registered streamed output and valid. valid is asserted only when rk_byte_r updates.
    signal rk_byte_r  : byte_t := (others => '0');
    signal rk_valid_r : std_logic := '0';

    --------------------------------------------------------------------
    -- S-box component (single shared instance)
    -- Used only for g() computation (SubWord of RotWord(w3)).
    --------------------------------------------------------------------
    component aes_sbox_cf is
        port(
            byte_in  : in  std_logic_vector(7 downto 0);
            usage    : in  std_logic;
            byte_out : out std_logic_vector(7 downto 0)
        );
    end component;

    signal sbox_in    : byte_t := (others => '0');
    signal sbox_out   : byte_t;
    signal sbox_usage : std_logic := '0';
    
    -- Delayed output
    type pipe_t is array (0 to 3) of std_logic_vector(7 downto 0);
    signal dly_pipe  : pipe_t := (others => (others => '0'));

    -- RotWord(w3) mapping for the last word bytes [12..15] of curr_key:
    -- w3 bytes = [b12, b13, b14, b15]
    -- RotWord(w3) = [b13, b14, b15, b12]
    function rotw3_byte(k : byte_array16_t; step : unsigned(1 downto 0)) return byte_t is
    begin
        case to_integer(step) is
            when 0 => return k(13);
            when 1 => return k(14);
            when 2 => return k(15);
            when others => return k(12);
        end case;
    end function;

begin

    --------------------------------------------------------------------
    -- Output assignments and lean tie-offs
    --------------------------------------------------------------------
    roundkey_byte_out <= rk_byte_r;
    roundkey_valid    <= rk_valid_r;

    -- busy is asserted while streaming round 0 or generating subsequent rounds
    busy <= '1' when (state = OUT_ROUND0 or state = G_FILL or state = GEN_BYTES) else '0';

    -- done is asserted after round 10 generation completes
    done <= '1' when (state = DONE_ST) else '0';

    -- Indices removed for lean implementation
    round_idx_out <= (others => '0');
    byte_idx_out  <= (others => '0');

    -- Debug outputs removed for lean implementation
    roundkey_block_out   <= (others => '0');
    roundkey_block_valid <= '0';
    last_roundkey_out    <= (others => '0');

    --------------------------------------------------------------------
    -- S-box input selection
    -- Forward S-box is used (usage='0'). Input is selected from RotWord(w3).
    --------------------------------------------------------------------
    sbox_usage <= '0';
    sbox_in    <= rotw3_byte(curr_key, g_step);

    u_sbox: aes_sbox_cf
        port map(
            byte_in  => sbox_in,
            usage    => sbox_usage,
            byte_out => sbox_out
        );

    --------------------------------------------------------------------
    -- Main sequential process
    --------------------------------------------------------------------
    process(clk)
        variable start_pulse  : std_logic;
        variable target_round : integer range 1 to 10;

        variable idx  : integer range 0 to 15;
        variable oldb : byte_t;
        variable genb : byte_t;
        variable pidx : integer range 0 to 3;
    begin
        if rising_edge(clk) then
            
            -- Default: deassert valid each cycle; assert only on a new output byte
            rk_valid_r <= '0';

            -- Start edge detect
            start_pulse := start and (not start_d);
            start_d     <= start;

            if rst = '1' then
                -- Synchronous reset of state and internal storage/counters
                state <= IDLE;

                curr_key <= (others => (others => '0'));
                g_cache  <= (others => (others => '0'));
                prev4    <= (others => (others => '0'));

                round_no <= (others => '0');
                byte_no  <= (others => '0');
                g_step   <= (others => '0');
                p4       <= (others => '0');
                start_d  <= '0';

                rk_byte_r  <= (others => '0');
                rk_valid_r <= '0';

            else
                case state is

                    when IDLE =>
                        -- Latch the 128-bit input key into byte array form on start pulse
                        if start_pulse = '1' then
                            for i in 0 to 15 loop
                                curr_key(i) <= key_in(127 - i*8 downto 120 - i*8);
                            end loop;

                            -- Initialise internal state for round 0 streaming
                            g_cache  <= (others => (others => '0'));
                            prev4    <= (others => (others => '0'));
                            round_no <= (others => '0');
                            byte_no  <= (others => '0');
                            g_step   <= (others => '0');
                            p4       <= (others => '0');

                            state <= OUT_ROUND0;
                        end if;

                    when OUT_ROUND0 =>
                        -- Stream the initial key (round 0 key), 16 bytes
                        idx := to_integer(byte_no);

                        rk_byte_r  <= curr_key(idx);
                        rk_valid_r <= '1';

                        if idx = 15 then
                            -- After byte 15, begin g() computation for round 1
                            byte_no <= (others => '0');
                            g_step  <= (others => '0');
                            state   <= G_FILL;
                        else
                            byte_no <= byte_no + 1;
                        end if;

                    when G_FILL =>
                        -- Build g_cache over 4 cycles using the S-box output.
                        -- target_round = round_no + 1 (ranges 1..10).
                        target_round := to_integer(round_no) + 1;

                        case to_integer(g_step) is
                            when 0 => g_cache(0) <= sbox_out xor RCON_B(target_round);
                            when 1 => g_cache(1) <= sbox_out;
                            when 2 => g_cache(2) <= sbox_out;
                            when others => g_cache(3) <= sbox_out;
                        end case;

                        if to_integer(g_step) = 3 then
                            -- After completing g_cache[3], begin byte generation
                            byte_no <= (others => '0');
                            p4      <= (others => '0');
                            prev4   <= (others => (others => '0'));
                            state   <= GEN_BYTES;
                        else
                            g_step <= g_step + 1;
                        end if;

                    when GEN_BYTES =>
                        -- Generate next round key bytes and stream them.
                        -- For i=0..3:   new[i] = old[i] XOR g_cache[i]
                        -- For i=4..15:  new[i] = old[i] XOR new[i-4] (held in prev4)
                        target_round := to_integer(round_no) + 1;
                        idx  := to_integer(byte_no);
                        pidx := to_integer(p4);

                        oldb := curr_key(idx);

                        if idx = 0 then
                            genb := oldb xor g_cache(0);
                        elsif idx = 1 then
                            genb := oldb xor g_cache(1);
                        elsif idx = 2 then
                            genb := oldb xor g_cache(2);
                        elsif idx = 3 then
                            genb := oldb xor g_cache(3);
                        else
                            genb := oldb xor prev4(pidx);
                        end if;

                        -- Update working key in-place
                        curr_key(idx) <= genb;

                        -- Update recurrence buffer (new[i-4]) and rolling pointer
                        prev4(pidx) <= genb;
                        p4 <= p4 + 1;  -- wraps at 2 bits

                        -- Stream generated byte
                        rk_byte_r  <= genb;
                        rk_valid_r <= '1';

                        if idx = 15 then
                            -- Completed this round key (16 bytes)
                            round_no <= to_unsigned(target_round, 4);

                            byte_no <= (others => '0');
                            g_step  <= (others => '0');
                            p4      <= (others => '0');

                            if target_round = 10 then
                                -- AES-128 generates 11 round keys (round 0..10)
                                state <= DONE_ST;
                            else
                                -- Compute next g() for following round
                                state <= G_FILL;
                            end if;
                        else
                            byte_no <= byte_no + 1;
                        end if;

                    when DONE_ST =>
                        -- Hold done high; restart on a new start pulse
                        if start_pulse = '1' then
                            for i in 0 to 15 loop
                                curr_key(i) <= key_in(127 - i*8 downto 120 - i*8);
                            end loop;

                            g_cache  <= (others => (others => '0'));
                            prev4    <= (others => (others => '0'));
                            round_no <= (others => '0');
                            byte_no  <= (others => '0');
                            g_step   <= (others => '0');
                            p4       <= (others => '0');

                            state <= OUT_ROUND0;
                        end if;

                end case;
            end if;
        end if;
    end process;

end architecture rtl;
