library ieee;
use ieee.std_logic_1164.all;

library std;
use std.env.all;

-- Directed testbench for the serial ShiftRows / InvShiftRows block.
-- The bench streams one full AES state plus extra padding cycles so the SRL
-- implementation has time to emit the permuted 16-byte result sequence.
entity shifter_serial_tb is
end entity shifter_serial_tb;

architecture sim of shifter_serial_tb is
    constant CLK_PERIOD : time := 10 ns;

    type byte_array16_t is array (0 to 15) of std_logic_vector(7 downto 0);

    -- Column-major AES state bytes.
    constant INPUT_BYTES : byte_array16_t := (
        x"00", x"11", x"22", x"33",
        x"44", x"55", x"66", x"77",
        x"88", x"99", x"AA", x"BB",
        x"CC", x"DD", x"EE", x"FF"
    );

    -- Expected ShiftRows output ordering.
    constant EXPECTED_FWD : byte_array16_t := (
        x"00", x"55", x"AA", x"FF",
        x"44", x"99", x"EE", x"33",
        x"88", x"DD", x"22", x"77",
        x"CC", x"11", x"66", x"BB"
    );

    -- Expected inverse ShiftRows output ordering.
    constant EXPECTED_INV : byte_array16_t := (
        x"00", x"DD", x"AA", x"77",
        x"44", x"11", x"EE", x"BB",
        x"88", x"55", x"22", x"FF",
        x"CC", x"99", x"66", x"33"
    );

    signal clk      : std_logic := '0';
    signal ce       : std_logic := '0';
    signal rst      : std_logic := '1';
    signal inverse  : std_logic := '0';
    signal state_in : std_logic_vector(7 downto 0) := (others => '0');
    signal state_out : std_logic_vector(7 downto 0);
    signal done     : std_logic;
begin

    clk <= not clk after CLK_PERIOD / 2;

    dut : entity work.shifter_serial
        generic map (
            support_inverse => true
        )
        port map (
            state_in  => state_in,
            state_out => state_out,
            ce        => ce,
            clk       => clk,
            rst       => rst,
            inverse   => inverse,
            done      => done
        );

    stim : process
        variable captured : byte_array16_t;

        procedure run_case(
            constant inv_mode : std_logic;
            constant expected : byte_array16_t;
            constant case_name : string
        ) is
        begin
            -- Reset between forward and inverse cases to clear SRL history.
            inverse <= inv_mode;
            ce <= '0';
            rst <= '1';
            state_in <= (others => '0');
            wait until rising_edge(clk);
            rst <= '0';
            wait until rising_edge(clk);

            for step in 0 to 31 loop
                if step < 16 then
                    state_in <= INPUT_BYTES(step);
                else
                    -- Flush the delayed bytes out of the SRL structure.
                    state_in <= (others => '0');
                end if;

                ce <= '1';
                wait until rising_edge(clk);

                if (step >= 12) and (step <= 27) then
                    captured(step - 12) := state_out;
                end if;
            end loop;

            ce <= '0';
            wait for CLK_PERIOD;

            for i in 0 to 15 loop
                assert captured(i) = expected(i)
                    report case_name & " mismatch at byte " & integer'image(i) &
                           ": got " & to_hstring(captured(i)) &
                           " expected " & to_hstring(expected(i))
                    severity failure;
            end loop;
        end procedure;
    begin
        -- Verify both byte permutations generated by the shared hardware.
        run_case('0', EXPECTED_FWD, "ShiftRows");
        run_case('1', EXPECTED_INV, "InvShiftRows");

        report "shifter_serial_tb PASSED" severity note;
        finish;
    end process;

end architecture sim;
